// Offline precache list generator. Run: node dev/precache-gen.mjs  (writes ./precache.js)
// test/precache.test.js fails when precache.js is stale, so the list is never hand-edited.
import { createHash } from 'node:crypto';
import { readdirSync, readFileSync, writeFileSync, statSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

const SKIP = /(\.md|@2x\.webp|\.DS_Store)$|^assets\/music\//; // lazy / non-asset files (AHI-035, AHI-050)
const walk = (root, dir) => readdirSync(join(root, dir)).flatMap((n) => {
  const p = `${dir}/${n}`;
  return statSync(join(root, p)).isDirectory() ? walk(root, p) : [p];
});

export function buildPrecache(root = '.') {
  const assets = walk(root, 'assets').filter((p) => !SKIP.test(p)).sort();
  const srcs = readdirSync(join(root, 'src')).filter((f) => f.endsWith('.js')).sort();
  const shell = ['style.css', ...srcs.map((f) => `src/${f}`)];
  const html = readFileSync(join(root, 'index.html'), 'utf8');
  const three = /"three":\s*"([^"]+)"/.exec(html)?.[1];
  const base = /^(.*\/three@[^/]+)\/build\//.exec(three ?? '')?.[1];
  if (!base) throw new Error('index.html importmap: "three" address not found');
  const addons = new Set();
  for (const f of srcs) for (const m of readFileSync(join(root, 'src', f), 'utf8').matchAll(/from\s+'three\/addons\/([^']+)'/g)) addons.add(m[1]);
  const cdn = [three, ...[...addons].sort().map((a) => `${base}/examples/jsm/${a}`)];
  const h = createHash('sha1');
  for (const p of assets) h.update(p).update('\0').update(readFileSync(join(root, p)));
  return { rev: h.digest('hex').slice(0, 8), shell, assets, cdn };
}

const list = (a) => `[\n${a.map((x) => `  ${JSON.stringify(x)},`).join('\n')}\n]`;
export function render({ rev, shell, assets, cdn }) {
  return `// AUTO-GENERATED by: node dev/precache-gen.mjs (do not edit; test/precache.test.js checks it is current)
self.ASSETS_REV = ${JSON.stringify(rev)};
self.SHELL_FILES = ${list(shell)};
self.ASSET_URLS = ${list(assets)};
self.CDN_URLS = ${list(cdn)};
`;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const out = render(buildPrecache('.'));
  writeFileSync('precache.js', out);
  console.log(`precache.js: ${out.split('\n').length} lines`);
}
